### ISSUE TITLE
Raft实现中有个问题交流一下！

### ISSUE THREAD

**Issue by tanmq** [Zhang626/MIT-6.824-2016#3]
假如ABC三个节点，A是leader！
突然间网络断了，AB可以通信，C自己单独出来了！
于是：
AB正常服务，C自己成为了“候选人”！
按照代码逻辑，C只能拿到自己的票，所以身份一直是候选人loop！C的term一直不停的增加！
然后若干时间，网络恢复了！恰好那时候C又发起了RequestVote。而这时候C的term都比AB大，
AB自动成为FOLLOWER！（这个应该是错误的！）

我上面描述的场景代码中有解决么？还是我看漏了？

**Comment by tanmq** [comment]
![image](https://user-images.githubusercontent.com/3056279/31768468-219d56c6-b495-11e7-84a3-c4e4bb957968.png)
在RequestVote函数中的这段代码应该可以去掉，就可以解决我上面那个问题！按照log的标准走！
似乎在论文中也没有提到要实现上图的逻辑！

**Comment by ShaneHeX** [comment]
不会的，服务器会全部变成候选人，然后term一杨后重新选举，会根据log选取何时的候选人同步log

**Comment by ShaneHeX** [comment]
c不会拿到多数票，所以在投票阶段投了其他人一票并变成了follower

**Comment by ShaneHeX** [comment]
细看了下论文，提到了，在那个表里面列了每个函数如何处理参数，对着写就好了，不用注释

**Comment by ShaneHeX** [comment]
我的解决方法是在投票的时候拿到了多数反对票就变成follower，c没log拿不到票

**Comment by tanmq** [comment]
是的，我错了。虽然AB变follower了，但是C拿不到选票，这时候AB的term追上C了，那么下次AB发起投票便能重新获得leader。

**Comment by shili1992** [comment]
raft要求新选出来的leader  必须包含全部已经提交的数据， 因此 A 和B不会投票给C.
